export const en = {
  brand: "Poker Academy",
  "nav.home": "Home",
  "nav.lessons": "Lessons",
  "nav.progress": "Progress",
  "footer.note": "Learn. Play. Improve.",

  "home.eyebrow": "FROM ZERO TO CONFIDENT",
  "home.title.1": "Learn ",
  "home.title.em": "poker",
  "home.title.2": " the smart way.",
  "home.lead": "Seven interactive lessons, graded exercises, and saved progress. No fluff — just the essentials to start strong at the tables.",
  "home.cta.start": "Start lessons",
  "home.cta.progress": "View progress",
  "home.stats.lessons": "Lessons",
  "home.stats.exercises": "Exercises",
  "home.stats.languages": "Languages",

  "lessons.title": "Lessons",
  "lessons.subtitle": "Pick a lesson. Each module ends with a graded exercise.",
  "lessons.continue": "Continue",
  "lessons.start": "Start",
  "lessons.review": "Review",
  "lessons.done": "Done",
  "lessons.score": "Score",
  "lessons.back": "← Back to lessons",
  "lessons.next": "Next lesson →",
  "lessons.toExercise": "Take the exercise →",
  "lessons.lesson": "Lesson",

  "l1.title": "Table positions",
  "l1.desc": "Learn the order of positions starting from the button: BU, CO, HJ, MP, UTG+2, UTG+1, UTG.",
  "l2.title": "Preflop and flop actions",
  "l2.desc": "Fold, check, call, bet, raise, all-in — when and how each is used.",
  "l3.title": "Pot and stack",
  "l3.desc": "Understand the pot and the stack, and why the ratio matters.",
  "l4.title": "Reading your hand",
  "l4.desc": "With 5 cards, find the best 5-card combination and name it.",
  "l5.title": "Hand strength",
  "l5.desc": "Rank 5-card compositions from strongest to weakest.",
  "l6.title": "Draws: flush & straight",
  "l6.desc": "Spot a flush draw or a straight draw and estimate your odds.",
  "l7.title": "Choosing your bet",
  "l7.desc": "Match your bet to the pot size — pot, ½ pot, ⅓ pot.",

  "ex.question": "Question",
  "ex.of": "of",
  "ex.validate": "Submit",
  "ex.next": "Next",
  "ex.finish": "Finish",
  "ex.correct": "Correct",
  "ex.wrong": "Wrong",
  "ex.explanation": "Explanation",
  "ex.retry": "Retry",
  "ex.toLesson": "Back to lesson",
  "ex.toLessons": "All lessons",
  "ex.score.title": "Exercise complete",
  "ex.score.outOf": "correct answers",
  "ex.score.recap": "Question recap",
  "ex.correctAnswer": "Correct answer:",

  "score.perfect": "Flawless. Clean work.",
  "score.great": "Solid. You've got it.",
  "score.ok": "Not bad. Review a couple of spots.",
  "score.low": "Worth revisiting the lesson.",

  // Lesson 1
  "l1.p1": "At a 7-handed poker table, each seat has a name. Position determines when you act: the later you play, the more information you have on your opponents.",
  "l1.h.order": "Position order",
  "l1.p2": "Start from the button (BU) and go clockwise. Here's the order, from latest to earliest:",
  "l1.li.bu": "<strong>BU (Button)</strong> — The button. Best position; you act last postflop.",
  "l1.li.co": "<strong>CO (Cut-Off)</strong> — Right before the button. Excellent position.",
  "l1.li.hj": "<strong>HJ (Hi-Jack)</strong> — Right before the cut-off. Comfortable position.",
  "l1.li.mp": "<strong>MP (Middle Position)</strong> — Mid-table position.",
  "l1.li.u2": "<strong>UTG+2</strong> — Third to act.",
  "l1.li.u1": "<strong>UTG+1</strong> — Second to act.",
  "l1.li.u0": "<strong>UTG (Under The Gun)</strong> — First to act preflop. Hardest position.",
  "l1.callout": "Tip: \"Under The Gun\" means under pressure. You act first, with zero information.",

  "l1.ex.q1": "Which is the latest position at the table?",
  "l1.ex.q1.exp": "The Button (BU) acts last postflop. It's the most advantageous position.",
  "l1.ex.q2": "What does UTG stand for?",
  "l1.ex.q2.exp": "UTG = Under The Gun. It's the first player to act preflop.",
  "l1.ex.q3": "Going from the button, which position acts right BEFORE the BU postflop?",
  "l1.ex.q3.exp": "The Cut-Off (CO) acts just before the button. It's the 2nd best position.",
  "l1.ex.q4": "Where is HJ (Hi-Jack) in order from the button?",
  "l1.ex.q4.exp": "From the button: BU → CO → HJ. HJ is the 3rd position to act postflop.",
  "l1.ex.q5": "Which position is generally hardest to play?",
  "l1.ex.q5.exp": "UTG is the toughest: you play first with no information.",

  // Lesson 2
  "l2.p1": "On each betting round you have choices. Your options depend on what happened before you.",
  "l2.h.actions": "Possible actions",
  "l2.li.fold": "<strong>Fold</strong> — You give up your hand. You lose what you've already bet.",
  "l2.li.check": "<strong>Check</strong> — You pass without betting. Only allowed if no one bet before you.",
  "l2.li.call": "<strong>Call</strong> — You match the current bet to stay in.",
  "l2.li.bet": "<strong>Bet</strong> — You're the first to put money in this round.",
  "l2.li.raise": "<strong>Raise</strong> — You increase the current bet.",
  "l2.li.allin": "<strong>All-in</strong> — You push your whole stack in.",
  "l2.h.preflop": "Preflop",
  "l2.p2": "Before the flop, the big blind is already in. You can't check unless you're the big blind and no one raised. Your options: fold, call, raise, all-in.",
  "l2.h.flop": "Flop, turn and river",
  "l2.p3": "Postflop, no forced blind. If no one bet, you can check. Otherwise: fold, call, raise.",
  "l2.callout": "Simple rule: you can only check if no one has bet before you on this round.",

  "l2.ex.q1": "No one has bet this round. Which action is NOT available preflop (you're not the big blind)?",
  "l2.ex.q1.exp": "Preflop the big blind is already in, so you must at least call — check is not allowed unless you're BB with no raise.",
  "l2.ex.q2": "A player bet before you on the flop. What does \"raise\" mean?",
  "l2.ex.q2.exp": "Raising means increasing the current bet, not just calling it.",
  "l2.ex.q3": "You're in the big blind, no raise preflop. You can:",
  "l2.ex.q3.exp": "In BB with no raise, you have the check option (or raise). No need to add more.",
  "l2.ex.q4": "What happens when you fold?",
  "l2.ex.q4.exp": "You discard your cards. You can't win this hand and your existing bet stays in the pot.",
  "l2.ex.q5": "On the flop, no one has bet before you. What are your options?",
  "l2.ex.q5.exp": "No bet before you = you can check (free) or bet (start the betting).",

  // Lesson 3
  "l3.p1": "Two key concepts you should track every hand: the pot and your stack.",
  "l3.h.pot": "The pot",
  "l3.p2": "The pot is the money in the middle of the table — all bets from this hand. The winner takes it.",
  "l3.h.stack": "The stack",
  "l3.p3": "Your stack is everything you have in front of you. It caps how much you can bet.",
  "l3.h.ratio": "Stack-to-pot ratio (SPR)",
  "l3.p4": "SPR = stack ÷ pot. A low SPR (≤ 3) often means all-in is close; a high SPR (≥ 10) calls for caution.",
  "l3.callout": "Example: pot = 100, your stack = 300, SPR = 3. With a mid pair you're often pot-committed.",

  "l3.ex.q1": "Pot = 200. Your stack = 50. What's true?",
  "l3.ex.q1.exp": "Your stack is smaller than the pot. You're likely short and your max bet is 50.",
  "l3.ex.q2": "Pot = 100, your stack = 500. What's the SPR?",
  "l3.ex.q2.exp": "SPR = stack ÷ pot = 500 ÷ 100 = 5.",
  "l3.ex.q3": "Why is SPR useful?",
  "l3.ex.q3.exp": "SPR helps decide commitment: low SPR = more willing to go all-in, high SPR = more caution.",
  "l3.ex.q4": "You jam all-in, pot was 50 and your stack 200. The pot before opponent calls is:",
  "l3.ex.q4.exp": "Existing pot (50) + your all-in (200) = 250 before opponent acts.",
  "l3.ex.q5": "Your stack dropped by 80, you didn't bet. Why?",
  "l3.ex.q5.exp": "If your stack drops without action, it's likely the blinds or antes were posted.",

  // Lesson 4
  "l4.p1": "At showdown your hand is the best 5-card combination from your cards + the board. To train, we give you 5 cards directly: find the combination.",
  "l4.h.combos": "Combinations (strongest to weakest)",
  "l4.li.sf": "<strong>Straight Flush</strong> — 5 consecutive cards of the same suit.",
  "l4.li.4k": "<strong>Four of a Kind</strong> — 4 cards of the same rank.",
  "l4.li.fh": "<strong>Full House</strong> — A trip + a pair.",
  "l4.li.fl": "<strong>Flush</strong> — 5 cards of the same suit.",
  "l4.li.st": "<strong>Straight</strong> — 5 consecutive cards.",
  "l4.li.3k": "<strong>Three of a Kind</strong> — 3 cards of the same rank.",
  "l4.li.2p": "<strong>Two Pair</strong> — Two distinct pairs.",
  "l4.li.1p": "<strong>Pair</strong> — Two cards of the same rank.",
  "l4.li.hc": "<strong>High Card</strong> — No combination, highest card wins.",
  "l4.callout": "The Ace is special: it can be high (10-J-Q-K-A) or low (A-2-3-4-5, the \"wheel\").",

  "l4.ex.prompt": "What's the combination of this 5-card hand?",

  "l5.p1": "You know the names — now you need to know which beats which. The order is universal — memorize it.",
  "l5.h.order": "The exact order",
  "l5.p2": "From strongest to weakest: Straight Flush > Four of a Kind > Full House > Flush > Straight > Three of a Kind > Two Pair > Pair > High Card.",
  "l5.callout": "Memory hook: rarer = stronger. Four of a kind is rarer than a full house, so it beats it.",

  "l5.ex.prompt": "Rank these 5 hands from strongest (1) to weakest (5).",

  "l6.p1": "A \"draw\" is a hand that isn't made yet but could become very strong with a good card on the turn or river.",
  "l6.h.flush": "Flush draw",
  "l6.p2": "You have 4 cards of the same suit, one short of a flush. 9 cards can help (the remaining 9 of that suit). About 35% to hit on turn + river.",
  "l6.h.straight": "Straight draw",
  "l6.p3": "Two types: <strong>gutshot</strong> — you need a middle card (4 outs, ~17%); <strong>open-ended</strong> — you can complete on either end (8 outs, ~32%).",
  "l6.callout": "Counting outs (cards that help) is the basics: one out ≈ 4% by the river (rule of 4).",

  "l6.ex.q1": "You have 4 cards of the same suit after the flop. How many outs?",
  "l6.ex.q1.exp": "13 cards per suit, you see 4, so 13 − 4 = 9 outs.",
  "l6.ex.q2": "Your hand + board form 7-8-9-10. What kind of draw?",
  "l6.ex.q2.exp": "A 6 or J completes it — open-ended draw, 8 outs.",
  "l6.ex.q3": "Hand + board: 5-7-8-9. What kind of straight draw?",
  "l6.ex.q3.exp": "Missing the 6 in the middle — gutshot, 4 outs.",
  "l6.ex.q4": "Roughly what odds to hit a flush on turn or river with 9 outs?",
  "l6.ex.q4.exp": "Rule of 4: 9 × 4 ≈ 36%, about 35%.",
  "l6.ex.q5": "You have an open-ended straight draw. How many outs?",
  "l6.ex.q5.exp": "Open-ended = complete on both ends = 8 outs.",

  "l7.p1": "A good bet size sends the right message while protecting your stack. The reference is always the pot.",
  "l7.h.sizes": "Standard sizes",
  "l7.li.s1": "<strong>⅓ pot</strong> — Small bet. For traps or thin value.",
  "l7.li.s2": "<strong>½ pot</strong> — Standard bet. Good to value-bet a decent hand.",
  "l7.li.s3": "<strong>⅔ to ¾ pot</strong> — Beefy bet. For strong value or big bluffs.",
  "l7.li.s4": "<strong>Pot</strong> — Max standard size. Very aggressive.",
  "l7.li.s5": "<strong>Overbet (> pot)</strong> — Reserved for very specific spots (polarized range).",
  "l7.callout": "Good practice: your bet should fit the strength you want to represent — not too small (not credible), not too big (chases folds).",

  "l7.ex.prompt": "The pot is {pot}. Pick a bet close to the recommended size:",
  "l7.ex.feedback.good": "Bet sized in line with the pot.",
  "l7.ex.feedback.close": "Close, but not optimal.",
  "l7.ex.feedback.bad": "Too far from the recommended size.",
  "l7.ex.target": "Target",
  "l7.ex.yourBet": "Your bet",
  "l7.ex.pot": "Pot",

  "prog.title": "Progress",
  "prog.subtitle": "Your exercise history and overall stats.",
  "prog.stats.avg": "Average score",
  "prog.stats.attempts": "Exercises taken",
  "prog.stats.lessons": "Lessons touched",
  "prog.stats.best": "Best score",
  "prog.history": "History",
  "prog.history.empty": "No exercise completed yet. Start with a lesson!",
  "prog.col.date": "Date",
  "prog.col.lesson": "Lesson",
  "prog.col.score": "Score",
  "prog.reset": "Reset my progress",
  "prog.reset.confirm": "Erase all progress? This is permanent.",
};
