export const fr = {
  brand: "Poker Academy",
  "nav.home": "Accueil",
  "nav.lessons": "Leçons",
  "nav.progress": "Progression",
  "footer.note": "Apprends. Joue. Progresse.",

  // Home
  "home.eyebrow": "DE ZÉRO À CONFIRMÉ",
  "home.title.1": "Apprends le ",
  "home.title.em": "poker",
  "home.title.2": " comme un pro.",
  "home.lead": "Sept leçons interactives, des exercices notés, et une progression sauvegardée. Pas de blabla, juste l'essentiel pour bien démarrer aux tables.",
  "home.cta.start": "Commencer les leçons",
  "home.cta.progress": "Voir ma progression",
  "home.stats.lessons": "Leçons",
  "home.stats.exercises": "Exercices",
  "home.stats.languages": "Langues",

  // Lessons list
  "lessons.title": "Leçons",
  "lessons.subtitle": "Choisis une leçon. Chaque module se termine par un exercice noté.",
  "lessons.continue": "Continuer",
  "lessons.start": "Commencer",
  "lessons.review": "Revoir",
  "lessons.done": "Complétée",
  "lessons.score": "Score",
  "lessons.back": "← Retour aux leçons",
  "lessons.next": "Leçon suivante →",
  "lessons.toExercise": "Faire l'exercice →",
  "lessons.lesson": "Leçon",

  // Lessons titles & descriptions
  "l1.title": "Les positions à la table",
  "l1.desc": "Apprends l'ordre des positions à partir du bouton : BU, CO, HJ, MP, UTG+2, UTG+1, UTG.",

  "l2.title": "Actions préflop et flop",
  "l2.desc": "Fold, check, call, bet, raise, all-in — quand et comment chaque action s'utilise.",

  "l3.title": "Le pot et le stack",
  "l3.desc": "Comprends ce que représentent le pot et le stack, et pourquoi le ratio compte.",

  "l4.title": "Lire ta main",
  "l4.desc": "Avec 5 cartes, trouve la meilleure combinaison de 5 cartes et donne-lui son nom.",

  "l5.title": "Forces des mains",
  "l5.desc": "Classe les compositions de 5 cartes de la plus forte à la plus faible.",

  "l6.title": "Tirages : flush & quinte",
  "l6.desc": "Reconnais un tirage couleur ou un tirage quinte et estime ta chance.",

  "l7.title": "Choisir sa mise",
  "l7.desc": "Adapte la taille de ta mise à la taille du pot — pot-bet, ½ pot, ⅓ pot.",

  // Common exercise UI
  "ex.question": "Question",
  "ex.of": "sur",
  "ex.validate": "Valider",
  "ex.next": "Suivant",
  "ex.finish": "Terminer",
  "ex.correct": "Bonne réponse",
  "ex.wrong": "Mauvaise réponse",
  "ex.explanation": "Explication",
  "ex.retry": "Recommencer",
  "ex.toLesson": "Revoir la leçon",
  "ex.toLessons": "Toutes les leçons",
  "ex.score.title": "Exercice terminé",
  "ex.score.outOf": "réponses correctes",
  "ex.score.recap": "Détail des questions",
  "ex.correctAnswer": "Bonne réponse :",

  // Score messages
  "score.perfect": "Sans-faute. Travail propre.",
  "score.great": "Solide. Tu maîtrises.",
  "score.ok": "Pas mal. Revois quelques points.",
  "score.low": "Reprends la leçon, ça vaut le coup.",

  // Lesson 1 - Positions
  "l1.p1": "À une table de poker à 7 joueurs, chaque siège a un nom. La position détermine quand tu joues : plus tu joues tard, plus tu as d'information sur les autres joueurs.",
  "l1.h.order": "L'ordre des positions",
  "l1.p2": "On part du bouton (BU) et on tourne dans le sens des aiguilles d'une montre. Voici l'ordre, du plus tard au plus tôt :",
  "l1.li.bu": "<strong>BU (Button)</strong> — Le bouton. Position la plus forte, tu parles en dernier postflop.",
  "l1.li.co": "<strong>CO (Cut-Off)</strong> — Juste avant le bouton. Excellente position.",
  "l1.li.hj": "<strong>HJ (Hi-Jack)</strong> — Avant le cut-off. Position confortable.",
  "l1.li.mp": "<strong>MP (Middle Position)</strong> — Position intermédiaire.",
  "l1.li.u2": "<strong>UTG+2</strong> — Troisième à parler.",
  "l1.li.u1": "<strong>UTG+1</strong> — Deuxième à parler.",
  "l1.li.u0": "<strong>UTG (Under The Gun)</strong> — Le premier à parler préflop. Position la plus difficile.",
  "l1.callout": "Astuce : « Under The Gun » signifie « sous le canon ». Tu parles en premier, sans aucune information sur les autres joueurs.",

  // Lesson 1 exercise
  "l1.ex.q1": "Quelle est la position la plus tardive à la table ?",
  "l1.ex.q1.exp": "Le bouton (BU) est la dernière position à parler postflop, c'est la plus avantageuse.",
  "l1.ex.q2": "Que signifie UTG ?",
  "l1.ex.q2.exp": "UTG = Under The Gun, littéralement « sous le canon ». C'est le premier joueur à parler préflop.",
  "l1.ex.q3": "Dans l'ordre, après le bouton (en partant et en revenant), quelle position parle juste AVANT le BU postflop ?",
  "l1.ex.q3.exp": "Le Cut-Off (CO) parle juste avant le bouton. C'est la 2e meilleure position.",
  "l1.ex.q4": "Place le HJ (Hi-Jack) dans l'ordre depuis le bouton.",
  "l1.ex.q4.exp": "Depuis le bouton : BU → CO → HJ. Le HJ est la 3e position à parler postflop.",
  "l1.ex.q5": "Quelle position est globalement la plus difficile à jouer ?",
  "l1.ex.q5.exp": "UTG est la position la plus difficile : tu joues en premier sans information.",

  // Lesson 2 - Actions
  "l2.p1": "À chaque tour d'enchères, tu as plusieurs choix. Tes options dépendent de ce qui s'est passé avant toi.",
  "l2.h.actions": "Les actions possibles",
  "l2.li.fold": "<strong>Fold (se coucher)</strong> — Tu abandonnes ta main. Tu perds ce que tu as déjà misé.",
  "l2.li.check": "<strong>Check (parole)</strong> — Tu passes ton tour sans miser. Possible seulement si personne n'a misé avant toi.",
  "l2.li.call": "<strong>Call (suivre)</strong> — Tu paies la mise en cours pour rester dans le coup.",
  "l2.li.bet": "<strong>Bet (miser)</strong> — Tu mises le premier sur ce tour.",
  "l2.li.raise": "<strong>Raise (relancer)</strong> — Tu augmentes la mise déjà en jeu.",
  "l2.li.allin": "<strong>All-in (tapis)</strong> — Tu mises tout ton stack.",
  "l2.h.preflop": "Préflop",
  "l2.p2": "Avant le flop, la grosse blinde est déjà en jeu. Tu ne peux donc pas « check » à part si tu es toi-même la grosse blinde et que personne n'a relancé. Tes options : fold, call, raise, all-in.",
  "l2.h.flop": "Au flop, turn et river",
  "l2.p3": "Après le flop, plus de blinde forcée. Si personne n'a misé, tu peux check. Sinon tu choisis entre fold, call ou raise.",
  "l2.callout": "Règle simple : tu ne peux check que si personne n'a misé avant toi sur ce tour.",

  "l2.ex.q1": "Personne n'a misé sur ce tour. Quelle action n'est pas possible préflop pour toi (tu n'es pas la grosse blinde) ?",
  "l2.ex.q1.exp": "Préflop, la grosse blinde est déjà engagée, tu dois donc au moins suivre — le check n'est pas permis sauf si tu es BB sans relance.",
  "l2.ex.q2": "Un joueur a misé avant toi au flop. Que veut dire « relancer » ?",
  "l2.ex.q2.exp": "Relancer (raise) = augmenter la mise en jeu, pas seulement la suivre.",
  "l2.ex.q3": "Tu as la grosse blinde, personne n'a relancé préflop. Tu peux :",
  "l2.ex.q3.exp": "En BB sans relance, tu as l'option du check (ou raise). Pas besoin de payer plus.",
  "l2.ex.q4": "Que se passe-t-il quand tu fais fold ?",
  "l2.ex.q4.exp": "Tu jettes tes cartes. Tu ne peux plus gagner ce coup et ce que tu as déjà misé reste dans le pot.",
  "l2.ex.q5": "Au flop, personne n'a misé avant toi. Quelles options as-tu ?",
  "l2.ex.q5.exp": "Pas de mise avant toi = tu peux check (gratuit) ou bet (lancer la mise).",

  // Lesson 3 - Pot & Stack
  "l3.p1": "Deux notions fondamentales que tu dois suivre à chaque main : le pot et ton stack.",
  "l3.h.pot": "Le pot",
  "l3.p2": "Le pot est l'argent au centre de la table — la somme de toutes les mises de ce coup. Le gagnant remporte ce pot.",
  "l3.h.stack": "Le stack",
  "l3.p3": "Ton stack, c'est tout ce qu'il te reste devant toi. Il définit combien tu peux miser au maximum.",
  "l3.h.ratio": "Le ratio stack/pot (SPR)",
  "l3.p4": "Le SPR = stack ÷ pot. C'est un indicateur clé : un SPR faible (≤ 3) pousse à jouer all-in, un SPR élevé (≥ 10) demande de la prudence.",
  "l3.callout": "Exemple : pot = 100, ton stack = 300, SPR = 3. Avec une paire moyenne tu es souvent committed.",

  "l3.ex.q1": "Le pot contient 200. Tu as 50 dans ton stack. Que peut-on dire ?",
  "l3.ex.q1.exp": "Ton stack est plus petit que le pot. Tu es probablement short stack et la mise max sera 50.",
  "l3.ex.q2": "Pot = 100, ton stack = 500. Quel est le SPR ?",
  "l3.ex.q2.exp": "SPR = stack ÷ pot = 500 ÷ 100 = 5.",
  "l3.ex.q3": "Pourquoi le SPR est-il utile ?",
  "l3.ex.q3.exp": "Le SPR aide à décider l'engagement : SPR faible = on joue plus volontiers all-in, SPR élevé = prudence accrue.",
  "l3.ex.q4": "Si tu pousses all-in et que le pot était de 50 et ton stack de 200, le pot final avant call sera :",
  "l3.ex.q4.exp": "Pot existant (50) + ta mise all-in (200) = 250 dans le pot avant que ton adversaire ne paye.",
  "l3.ex.q5": "Ton stack diminue de 80, tu n'as pas misé. Que s'est-il passé ?",
  "l3.ex.q5.exp": "Si ton stack baisse sans action volontaire, c'est probablement les blindes ou antes qui sont passées sur toi.",

  // Lesson 4 - Reading hand
  "l4.p1": "Au showdown, ta main, c'est la meilleure combinaison de 5 cartes que tu peux faire à partir de tes cartes + le tableau. Pour s'entraîner, on te donne directement 5 cartes : trouve la combinaison.",
  "l4.h.combos": "Les combinaisons (de la plus forte à la plus faible)",
  "l4.li.sf": "<strong>Quinte flush</strong> — 5 cartes consécutives de la même couleur.",
  "l4.li.4k": "<strong>Carré</strong> — 4 cartes de même rang.",
  "l4.li.fh": "<strong>Full</strong> — Un brelan + une paire.",
  "l4.li.fl": "<strong>Couleur (Flush)</strong> — 5 cartes de la même couleur.",
  "l4.li.st": "<strong>Quinte (Straight)</strong> — 5 cartes consécutives.",
  "l4.li.3k": "<strong>Brelan</strong> — 3 cartes de même rang.",
  "l4.li.2p": "<strong>Deux paires</strong> — Deux paires différentes.",
  "l4.li.1p": "<strong>Paire</strong> — Deux cartes de même rang.",
  "l4.li.hc": "<strong>Hauteur</strong> — Aucune combinaison, on compare la plus haute carte.",
  "l4.callout": "L'As est spécial : il peut être haut (10-J-Q-K-A) ou bas (A-2-3-4-5, la « roue »).",

  "l4.ex.prompt": "Quelle est la combinaison de cette main de 5 cartes ?",

  // Lesson 5 - Hand strength ranking
  "l5.p1": "Tu connais les noms, maintenant il faut savoir laquelle bat laquelle. L'ordre est universel — apprends-le par cœur.",
  "l5.h.order": "L'ordre exact",
  "l5.p2": "De la plus forte à la plus faible : Quinte flush > Carré > Full > Couleur > Quinte > Brelan > Deux paires > Paire > Hauteur.",
  "l5.callout": "Astuce mnémo : plus une combinaison est rare, plus elle est forte. Un carré est plus rare qu'un full, donc plus fort.",

  "l5.ex.prompt": "Classe ces 5 mains de la plus forte (1) à la plus faible (5).",

  // Lesson 6 - Draws
  "l6.p1": "Un « tirage » est une main qui n'est pas encore faite mais qui peut devenir très forte avec une bonne carte au turn ou à la river.",
  "l6.h.flush": "Tirage couleur (flush draw)",
  "l6.p2": "Tu as 4 cartes de la même couleur, il t'en manque une pour faire couleur. Tu as 9 cartes qui peuvent t'aider (les 9 restantes de cette couleur). Environ 35% de toucher au turn + river.",
  "l6.h.straight": "Tirage quinte (straight draw)",
  "l6.p3": "Deux types : <strong>ventral (gutshot)</strong> — il te manque une carte au milieu (4 outs, ~17%) ; <strong>bilatéral (open-ended)</strong> — tu peux compléter des deux côtés (8 outs, ~32%).",
  "l6.callout": "Compter ses outs (cartes qui aident) est la base : un out vaut environ 4% au turn+river (règle des 4).",

  "l6.ex.q1": "Tu as 4 cartes de la même couleur après le flop. Combien d'outs ?",
  "l6.ex.q1.exp": "Il reste 13 cartes par couleur, tu en vois 4, donc 13 − 4 = 9 outs.",
  "l6.ex.q2": "Ton tableau + main forme 7-8-9-10. Quel type de tirage ?",
  "l6.ex.q2.exp": "Tu peux compléter avec un 6 ou un J — tirage bilatéral (open-ended), 8 outs.",
  "l6.ex.q3": "Ta main + tableau : 5-7-8-9. Quel type de tirage quinte ?",
  "l6.ex.q3.exp": "Il te manque le 6 au milieu — tirage ventral (gutshot), 4 outs.",
  "l6.ex.q4": "Environ quelle chance de toucher une couleur au turn ou à la river avec 9 outs ?",
  "l6.ex.q4.exp": "Règle des 4 : 9 × 4 ≈ 36%, environ 35%.",
  "l6.ex.q5": "Tu as un tirage quinte bilatéral. Combien d'outs ?",
  "l6.ex.q5.exp": "Tirage bilatéral = tu peux compléter des deux côtés = 8 outs.",

  // Lesson 7 - Bet sizing
  "l7.p1": "Choisir une bonne taille de mise, c'est faire passer le bon message tout en protégeant son stack. La référence, c'est toujours la taille du pot.",
  "l7.h.sizes": "Les tailles standards",
  "l7.li.s1": "<strong>⅓ pot</strong> — Petite mise. Pour piéger ou jouer mince.",
  "l7.li.s2": "<strong>½ pot</strong> — Mise standard. Bonne pour valoriser une main correcte.",
  "l7.li.s3": "<strong>⅔ à ¾ pot</strong> — Mise musclée. Pour valoriser une main forte ou bluffer fort.",
  "l7.li.s4": "<strong>Pot</strong> — Mise maximale standard. Très agressif.",
  "l7.li.s5": "<strong>Overbet (> pot)</strong> — À réserver à des spots très précis (top range polarisée).",
  "l7.callout": "Bonne pratique : ta mise doit être cohérente avec la force que tu veux représenter — ni trop petite (pas crédible), ni trop grosse (chassante).",

  "l7.ex.prompt": "Le pot fait {pot}. Choisis une mise proche de la taille recommandée :",
  "l7.ex.feedback.good": "Mise cohérente avec la taille du pot.",
  "l7.ex.feedback.close": "Pas loin, mais pas optimal.",
  "l7.ex.feedback.bad": "Trop éloigné de la taille recommandée.",
  "l7.ex.target": "Cible",
  "l7.ex.yourBet": "Ta mise",
  "l7.ex.pot": "Pot",

  // Progress page
  "prog.title": "Progression",
  "prog.subtitle": "Ton historique d'exercices et tes statistiques globales.",
  "prog.stats.avg": "Score moyen",
  "prog.stats.attempts": "Exercices faits",
  "prog.stats.lessons": "Leçons abordées",
  "prog.stats.best": "Meilleur score",
  "prog.history": "Historique",
  "prog.history.empty": "Aucun exercice complété pour l'instant. Commence par une leçon !",
  "prog.col.date": "Date",
  "prog.col.lesson": "Leçon",
  "prog.col.score": "Score",
  "prog.reset": "Réinitialiser ma progression",
  "prog.reset.confirm": "Effacer toute la progression ? Cette action est définitive.",
};
